-- bucket_index: 0 for non-sharded accounts (BANK_ACCOUNT, FEE_REVENUE, MERCHANT_*)
--               0~15 for CARD_NETWORK_RECEIVABLE shards
ALTER TABLE account ADD COLUMN bucket_index INT NOT NULL DEFAULT 0;

ALTER TABLE account DROP KEY uk_account_type_merchant_id;
ALTER TABLE account ADD UNIQUE KEY uk_account_bucket (account_type, merchant_id, bucket_index);

INSERT INTO account (account_type, account_class, merchant_id, balance, version, created_at, updated_at, bucket_index)
VALUES
    ('CARD_NETWORK_RECEIVABLE', 'ASSET', 'GLOBAL', 0, 0, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6),  1),
    ('CARD_NETWORK_RECEIVABLE', 'ASSET', 'GLOBAL', 0, 0, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6),  2),
    ('CARD_NETWORK_RECEIVABLE', 'ASSET', 'GLOBAL', 0, 0, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6),  3),
    ('CARD_NETWORK_RECEIVABLE', 'ASSET', 'GLOBAL', 0, 0, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6),  4),
    ('CARD_NETWORK_RECEIVABLE', 'ASSET', 'GLOBAL', 0, 0, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6),  5),
    ('CARD_NETWORK_RECEIVABLE', 'ASSET', 'GLOBAL', 0, 0, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6),  6),
    ('CARD_NETWORK_RECEIVABLE', 'ASSET', 'GLOBAL', 0, 0, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6),  7),
    ('CARD_NETWORK_RECEIVABLE', 'ASSET', 'GLOBAL', 0, 0, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6),  8),
    ('CARD_NETWORK_RECEIVABLE', 'ASSET', 'GLOBAL', 0, 0, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6),  9),
    ('CARD_NETWORK_RECEIVABLE', 'ASSET', 'GLOBAL', 0, 0, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), 10),
    ('CARD_NETWORK_RECEIVABLE', 'ASSET', 'GLOBAL', 0, 0, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), 11),
    ('CARD_NETWORK_RECEIVABLE', 'ASSET', 'GLOBAL', 0, 0, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), 12),
    ('CARD_NETWORK_RECEIVABLE', 'ASSET', 'GLOBAL', 0, 0, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), 13),
    ('CARD_NETWORK_RECEIVABLE', 'ASSET', 'GLOBAL', 0, 0, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), 14),
    ('CARD_NETWORK_RECEIVABLE', 'ASSET', 'GLOBAL', 0, 0, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), 15);
