INSERT INTO account (account_type, account_class, merchant_id, balance, version, created_at, updated_at, bucket_index)
VALUES
    ('FEE_REVENUE', 'REVENUE', 'GLOBAL', 0, 0, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6),  1),
    ('FEE_REVENUE', 'REVENUE', 'GLOBAL', 0, 0, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6),  2),
    ('FEE_REVENUE', 'REVENUE', 'GLOBAL', 0, 0, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6),  3),
    ('FEE_REVENUE', 'REVENUE', 'GLOBAL', 0, 0, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6),  4),
    ('FEE_REVENUE', 'REVENUE', 'GLOBAL', 0, 0, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6),  5),
    ('FEE_REVENUE', 'REVENUE', 'GLOBAL', 0, 0, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6),  6),
    ('FEE_REVENUE', 'REVENUE', 'GLOBAL', 0, 0, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6),  7),
    ('FEE_REVENUE', 'REVENUE', 'GLOBAL', 0, 0, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6),  8),
    ('FEE_REVENUE', 'REVENUE', 'GLOBAL', 0, 0, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6),  9),
    ('FEE_REVENUE', 'REVENUE', 'GLOBAL', 0, 0, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), 10),
    ('FEE_REVENUE', 'REVENUE', 'GLOBAL', 0, 0, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), 11),
    ('FEE_REVENUE', 'REVENUE', 'GLOBAL', 0, 0, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), 12),
    ('FEE_REVENUE', 'REVENUE', 'GLOBAL', 0, 0, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), 13),
    ('FEE_REVENUE', 'REVENUE', 'GLOBAL', 0, 0, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), 14),
    ('FEE_REVENUE', 'REVENUE', 'GLOBAL', 0, 0, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), 15);
