spring:
  application:
    name: fds
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:fds-mysql}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:fds}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${MYSQL_USER:fds}
    password: ${MYSQL_PASSWORD:fds}
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
